# Generated by Django 3.0.5 on 2020-05-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placiosite', '0002_auto_20200522_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'University'},
        ),
    ]
