# Generated by Django 3.0.5 on 2020-05-24 01:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('placiosite', '0003_auto_20200522_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostYourReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('budget', models.FloatField()),
                ('roomtype', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room')], default='Choose Your option', max_length=200)),
                ('comment', models.TextField()),
            ],
        ),
    ]
