# Generated by Django 3.0.5 on 2020-05-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placiosite', '0004_postyourreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postyourreq',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placiosite.City'),
        ),
        migrations.AlterField(
            model_name='postyourreq',
            name='roomtype',
            field=models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room')], max_length=200),
        ),
    ]
