# Generated by Django 3.0.5 on 2020-05-25 22:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('placiosite', '0005_auto_20200523_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('typeofproperty', models.CharField(choices=[('apartment', 'Apartment'), ('hostel', 'Student Hostel'), ('service', 'Service Apartment')], max_length=200)),
                ('NumberofBedrooms', models.FloatField()),
                ('ExpectedRent', models.FloatField()),
                ('currentStatus', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placiosite.City')),
            ],
        ),
    ]
