# Generated by Django 3.0.5 on 2020-05-28 06:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('placiosite', '0006_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(choices=[('advance', 'Advance'), ('rent', 'Rent')], max_length=200)),
                ('propertyname', models.CharField(max_length=200)),
                ('tenantId', models.FloatField(max_length=200)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
